export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <div className='flex flex-col md:flex-row h-full min-h-screen font-sans'>
    <html lang="en">
      <body>{children}</body>
    </html>
    </div>
    </>
  )
}
